services:
  py-rocket-base:
    image: ghcr.io/nmfs-opensci/container-images/py-rocket-base:latest
    container_name: py-rocket-base
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    command: >
      bash -c "jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''"
    environment:
      - JUPYTER_ENABLE_LAB=yes
