services:
  rstudio:
    container_name: rstudio-verse
    build: .
    ports:
      - "8787:8787"
    volumes:
      - ./.rstudio_config:/home/rstudio/.config/rstudio
      - ../../:/home/rstudio/workspace
    environment:
      - DISABLE_AUTH=true

