version: '3'
services:
  debris-database:
    container_name: esd-database
    image: gvenzl/oracle-xe
    ports: 
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    volumes:
      - ./db-vol:/opt/oracle/oradata
    hostname: database
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 100
  mission-app:
    container_name: mission-app
    restart: always
    depends_on:
      esd-database:
        condition: service_healthy
    volumes:
      - ./ords_secrets:/opt/oracle/variables
      - ./ords_config:/etc/ords/config
    ports:
      - 8181:8181
    image: container-registry.oracle.com/database/ords:latest
    environment:
      - DOCKER_REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME}
      - DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD}
      - CONN_STRING=${CONN_STRING}
networks:
  default:
    name: esd-database-network

