services:
  free-database:
    container_name: free-database
    restart: always
    image: gvenzl/oracle-free
    ports: 
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    volumes:
      - /workspaces/Open-Science-Codespaces/app/free-app/db-vol:/opt/oracle/oradata
    hostname: database
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 100
  ords-apex:
    container_name: ords-apex
    restart: always
    depends_on:
      free-database:
        condition: service_healthy
    volumes:
      - /workspaces/Open-Science-Codespaces/app/free-app/ords_secrets:/opt/oracle/variables
      - /workspaces/Open-Science-Codespaces/app/free-app/ords_config:/etc/ords/config
    ports:
      - 8181:8181
    image: container-registry.oracle.com/database/ords:latest
    environment:
      - ORACLE_DOCKER_REGISTRY_USERNAME=${ORACLE_DOCKER_REGISTRY_USERNAME}
      - ORACLE_DOCKER_REGISTRY_PASSWORD=${ORACLE_DOCKER_REGISTRY_PASSWORD}
      - CONN_STRING=${CONN_STRING}
