services:
  rshiny-app:
    container_name: rshiny-app
    image: rocker/shiny:latest
    ports:
      - "3838:3838"
    volumes:
      - ./.rstudio_config:/home/rstudio/.config/rstudio
      - ./workspace:/home/rstudio/workspace
      - ./other_dir:/other_dir

