services:
  rstudio:
    container_name: rstudio-geospatial
    image: rocker/geospatial:latest
    ports:
      - "8787:8787"
    volumes:
      - ./.rstudio_config:/home/rstudio/.config/rstudio
      - ./workspace:/home/rstudio/workspace
      - ./other_dir:/other_dir
    environment:
      - DISABLE_AUTH=true

